MODULE_NAME = "Client Settings"

NOTIFICATION_CHANNELS = [
    {"type": "email",    "label": "Email",             "icon": "mail"},
    {"type": "sms",      "label": "SMS",               "icon": "message-square"},
    {"type": "whatsapp", "label": "WhatsApp",          "icon": "message-circle"},
    {"type": "push",     "label": "Push Notification", "icon": "bell"},
    {"type": "in_app",   "label": "In-App",            "icon": "monitor"},
]

CREDENTIAL_TYPES = [
    {"type": "smtp",            "label": "SMTP",               "description": "Email delivery via SMTP"},
    {"type": "sms_gateway",     "label": "SMS Gateway",         "description": "SMS delivery provider"},
    {"type": "whatsapp_api",    "label": "WhatsApp API",        "description": "WhatsApp Business API"},
    {"type": "google_oauth",    "label": "Google OAuth",        "description": "Google SSO & Calendar"},
    {"type": "microsoft_oauth", "label": "Microsoft OAuth",     "description": "Microsoft SSO & Office 365"},
    {"type": "calendar",        "label": "Calendar Integration","description": "Calendar sync provider"},
    {"type": "storage",         "label": "Storage Provider",    "description": "File storage (S3, GCS, etc.)"},
    {"type": "custom_api",      "label": "Custom API",          "description": "Custom third-party API"},
]

MASTER_TYPES = [
    "country", "state", "city", "currency", "language",
    "employment_type", "blood_group", "marital_status",
    "gender", "document_type", "relationship_type",
]

MASTER_TYPE_LABELS = {
    "country":         "Countries",
    "state":           "States",
    "city":            "Cities",
    "currency":        "Currencies",
    "language":        "Languages",
    "employment_type": "Employment Types",
    "blood_group":     "Blood Groups",
    "marital_status":  "Marital Status",
    "gender":          "Gender",
    "document_type":   "Document Types",
    "relationship_type":"Relationship Types",
}

DEFAULT_MASTERS = {
    "employment_type": [
        {"code": "permanent",  "label": "Permanent"},
        {"code": "temporary",  "label": "Temporary"},
        {"code": "contract",   "label": "Contract"},
        {"code": "part_time",  "label": "Part Time"},
        {"code": "full_time",  "label": "Full Time"},
        {"code": "freelance",  "label": "Freelance"},
    ],
    "blood_group": [
        {"code": "A+",  "label": "A+"},
        {"code": "A-",  "label": "A-"},
        {"code": "B+",  "label": "B+"},
        {"code": "B-",  "label": "B-"},
        {"code": "AB+", "label": "AB+"},
        {"code": "AB-", "label": "AB-"},
        {"code": "O+",  "label": "O+"},
        {"code": "O-",  "label": "O-"},
    ],
    "marital_status": [
        {"code": "single",    "label": "Single"},
        {"code": "married",   "label": "Married"},
        {"code": "divorced",  "label": "Divorced"},
        {"code": "widowed",   "label": "Widowed"},
        {"code": "separated", "label": "Separated"},
    ],
    "gender": [
        {"code": "male",       "label": "Male"},
        {"code": "female",     "label": "Female"},
        {"code": "other",      "label": "Other"},
        {"code": "prefer_not", "label": "Prefer not to say"},
    ],
    "relationship_type": [
        {"code": "father",          "label": "Father"},
        {"code": "mother",          "label": "Mother"},
        {"code": "spouse",          "label": "Spouse"},
        {"code": "son",             "label": "Son"},
        {"code": "daughter",        "label": "Daughter"},
        {"code": "sibling",         "label": "Sibling"},
        {"code": "guardian",        "label": "Guardian"},
        {"code": "friend",          "label": "Friend"},
        {"code": "father_in_law",   "label": "Father-in-Law"},
        {"code": "mother_in_law",   "label": "Mother-in-Law"},
        {"code": "other",           "label": "Other"},
    ],
    "document_type": [
        {"code": "AADHAR",      "label": "Aadhaar Card"},
        {"code": "PAN",         "label": "PAN Card"},
        {"code": "PASSPORT",    "label": "Passport"},
        {"code": "DL",          "label": "Driving License"},
        {"code": "VOTER_ID",    "label": "Voter ID"},
        {"code": "RESUME",      "label": "Resume / CV"},
        {"code": "DEGREE",      "label": "Degree Certificate"},
        {"code": "DIPLOMA",     "label": "Diploma"},
        {"code": "MARKSHEET",   "label": "Mark Sheet"},
        {"code": "EXP_LETTER",  "label": "Experience Letter"},
        {"code": "OFFER_LETTER","label": "Offer Letter"},
        {"code": "SALARY_SLIP", "label": "Salary Slip"},
        {"code": "MED_CERT",    "label": "Medical Certificate"},
    ],
    "language": [
        {"code": "en", "label": "English"},
        {"code": "hi", "label": "Hindi"},
        {"code": "mr", "label": "Marathi"},
        {"code": "ta", "label": "Tamil"},
        {"code": "te", "label": "Telugu"},
        {"code": "kn", "label": "Kannada"},
        {"code": "gu", "label": "Gujarati"},
        {"code": "bn", "label": "Bengali"},
        {"code": "ml", "label": "Malayalam"},
        {"code": "pa", "label": "Punjabi"},
    ],
    "country": [
        {"code": "IN", "label": "India"},
        {"code": "US", "label": "United States"},
        {"code": "GB", "label": "United Kingdom"},
        {"code": "AE", "label": "United Arab Emirates"},
        {"code": "SG", "label": "Singapore"},
        {"code": "AU", "label": "Australia"},
        {"code": "CA", "label": "Canada"},
        {"code": "DE", "label": "Germany"},
        {"code": "FR", "label": "France"},
        {"code": "JP", "label": "Japan"},
        {"code": "NZ", "label": "New Zealand"},
        {"code": "ZA", "label": "South Africa"},
    ],
    "currency": [
        {"code": "INR", "label": "Indian Rupee",      "metadata": {"symbol": "₹"}},
        {"code": "USD", "label": "US Dollar",          "metadata": {"symbol": "$"}},
        {"code": "EUR", "label": "Euro",               "metadata": {"symbol": "€"}},
        {"code": "GBP", "label": "British Pound",      "metadata": {"symbol": "£"}},
        {"code": "AED", "label": "UAE Dirham",         "metadata": {"symbol": "AED"}},
        {"code": "SGD", "label": "Singapore Dollar",   "metadata": {"symbol": "S$"}},
        {"code": "AUD", "label": "Australian Dollar",  "metadata": {"symbol": "A$"}},
        {"code": "CAD", "label": "Canadian Dollar",    "metadata": {"symbol": "C$"}},
    ],
}
