"""Employee Management — constants."""

MODULE_NAME = "Organization Management"
MODULE_CODE = "EMPLOYEE"

# Employee Categories
EMPLOYEE_CATEGORY_EMPLOYEE    = "Employee"
EMPLOYEE_CATEGORY_INTERN      = "Intern"
EMPLOYEE_CATEGORY_CONSULTANT  = "Consultant"
EMPLOYEE_CATEGORY_CONTRACTOR  = "Contractor"
EMPLOYEE_CATEGORY_TRAINEE     = "Trainee"
EMPLOYEE_CATEGORY_APPRENTICE  = "Apprentice"
EMPLOYEE_CATEGORIES = [
    EMPLOYEE_CATEGORY_EMPLOYEE, EMPLOYEE_CATEGORY_INTERN,
    EMPLOYEE_CATEGORY_CONSULTANT, EMPLOYEE_CATEGORY_CONTRACTOR,
    EMPLOYEE_CATEGORY_TRAINEE, EMPLOYEE_CATEGORY_APPRENTICE,
]

# Employment Types
EMPLOYMENT_TYPE_PERMANENT  = "Permanent"
EMPLOYMENT_TYPE_TEMPORARY  = "Temporary"
EMPLOYMENT_TYPE_CONTRACT   = "Contract"
EMPLOYMENT_TYPE_PART_TIME  = "Part Time"
EMPLOYMENT_TYPE_FULL_TIME  = "Full Time"
EMPLOYMENT_TYPE_FREELANCE  = "Freelance"
EMPLOYMENT_TYPES = [
    EMPLOYMENT_TYPE_PERMANENT, EMPLOYMENT_TYPE_TEMPORARY,
    EMPLOYMENT_TYPE_CONTRACT, EMPLOYMENT_TYPE_PART_TIME,
    EMPLOYMENT_TYPE_FULL_TIME, EMPLOYMENT_TYPE_FREELANCE,
]

# Employment Statuses
STATUS_DRAFT         = "Draft"
STATUS_ACTIVE        = "Active"
STATUS_ON_LEAVE      = "On Leave"
STATUS_PROBATION     = "Probation"
STATUS_NOTICE_PERIOD = "Notice Period"
STATUS_RESIGNED      = "Resigned"
STATUS_TERMINATED    = "Terminated"
STATUS_RETIRED       = "Retired"
STATUS_INACTIVE      = "Inactive"
EMPLOYMENT_STATUSES = [
    STATUS_DRAFT, STATUS_ACTIVE, STATUS_ON_LEAVE, STATUS_PROBATION,
    STATUS_NOTICE_PERIOD, STATUS_RESIGNED, STATUS_TERMINATED,
    STATUS_RETIRED, STATUS_INACTIVE,
]

GENDERS           = ["Male", "Female", "Other", "Prefer not to say"]
MARITAL_STATUSES  = ["Single", "Married", "Divorced", "Widowed", "Separated"]
BLOOD_GROUPS      = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]

RELATIONSHIPS     = ["Father", "Mother", "Spouse", "Sibling", "Guardian", "Friend", "Other"]

# Activity actions
ACTION_CREATED             = "EMPLOYEE_CREATED"
ACTION_UPDATED             = "EMPLOYEE_UPDATED"
ACTION_ACTIVATED           = "EMPLOYEE_ACTIVATED"
ACTION_DEACTIVATED         = "EMPLOYEE_DEACTIVATED"
ACTION_STATUS_CHANGED      = "STATUS_CHANGED"
ACTION_DEPT_CHANGED        = "DEPARTMENT_CHANGED"
ACTION_DESIG_CHANGED       = "DESIGNATION_CHANGED"
ACTION_IMPORTED            = "EMPLOYEE_IMPORTED"
