"""add_industry_master_and_org_company_industry_fields

Revision ID: 0b02a3bf0a93
Revises: e1fb35631a4e
Create Date: 2026-06-29 14:35:19.633959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b02a3bf0a93'
down_revision: Union[str, None] = 'e1fb35631a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sub_industries', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_master')
    # ### end Alembic commands ###
