"""add hiring_manager and expected_joining_date to job_openings

Revision ID: 0fbb52c180b4
Revises: a4446dc13c91
Create Date: 2026-07-15 06:54:26.146564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fbb52c180b4'
down_revision: Union[str, None] = 'a4446dc13c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
