"""add_document_type_id_to_lead_documents

Revision ID: 115eedde2174
Revises: 4accaa0a5434
Create Date: 2026-06-30 09:00:50.257120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '115eedde2174'
down_revision: Union[str, None] = '4accaa0a5434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_documents', sa.Column('document_type_id', sa.String(length=36), nullable=True))
    op.alter_column('lead_documents', 'document_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_lead_documents_document_type_id'), 'lead_documents', ['document_type_id'], unique=False)
    op.create_foreign_key(None, 'lead_documents', 'client_document_types', ['document_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_documents', type_='foreignkey')
    op.drop_index(op.f('ix_lead_documents_document_type_id'), table_name='lead_documents')
    op.alter_column('lead_documents', 'document_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('lead_documents', 'document_type_id')
    # ### end Alembic commands ###
