"""portal_user_management

Revision ID: 1e7758f4eac0
Revises: ffbfbee23af8
Create Date: 2026-06-02 10:57:14.484164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e7758f4eac0'
down_revision: Union[str, None] = 'ffbfbee23af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_roles_client_id'), 'client_roles', ['client_id'], unique=False)
    op.create_index('ix_client_roles_client_name', 'client_roles', ['client_id', 'name'], unique=True)
    op.create_table('client_login_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('browser_info', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['client_admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_login_logs_client_id'), 'client_login_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_login_logs_created_at'), 'client_login_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_login_logs_user_id'), 'client_login_logs', ['user_id'], unique=False)
    op.create_table('client_portal_activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['client_admin_users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['client_admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_portal_activity_logs_actor_id'), 'client_portal_activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_client_portal_activity_logs_client_id'), 'client_portal_activity_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_portal_activity_logs_created_at'), 'client_portal_activity_logs', ['created_at'], unique=False)
    op.create_table('client_user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['client_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['client_admin_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('client_user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('browser_info', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logged_out_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['client_admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_user_sessions_client_id'), 'client_user_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_user_sessions_jti'), 'client_user_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_client_user_sessions_user_id'), 'client_user_sessions', ['user_id'], unique=False)
    op.add_column('client_admin_users', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('client_admin_users', sa.Column('profile_picture_url', sa.Text(), nullable=True))
    op.add_column('client_admin_users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_admin_users', 'last_login')
    op.drop_column('client_admin_users', 'profile_picture_url')
    op.drop_column('client_admin_users', 'display_name')
    op.drop_index(op.f('ix_client_user_sessions_user_id'), table_name='client_user_sessions')
    op.drop_index(op.f('ix_client_user_sessions_jti'), table_name='client_user_sessions')
    op.drop_index(op.f('ix_client_user_sessions_client_id'), table_name='client_user_sessions')
    op.drop_table('client_user_sessions')
    op.drop_table('client_user_roles')
    op.drop_index(op.f('ix_client_portal_activity_logs_created_at'), table_name='client_portal_activity_logs')
    op.drop_index(op.f('ix_client_portal_activity_logs_client_id'), table_name='client_portal_activity_logs')
    op.drop_index(op.f('ix_client_portal_activity_logs_actor_id'), table_name='client_portal_activity_logs')
    op.drop_table('client_portal_activity_logs')
    op.drop_index(op.f('ix_client_login_logs_user_id'), table_name='client_login_logs')
    op.drop_index(op.f('ix_client_login_logs_created_at'), table_name='client_login_logs')
    op.drop_index(op.f('ix_client_login_logs_client_id'), table_name='client_login_logs')
    op.drop_table('client_login_logs')
    op.drop_index('ix_client_roles_client_name', table_name='client_roles')
    op.drop_index(op.f('ix_client_roles_client_id'), table_name='client_roles')
    op.drop_table('client_roles')
    # ### end Alembic commands ###
