"""add client document types table and document_type_id fk

Revision ID: 4accaa0a5434
Revises: 0b02a3bf0a93
Create Date: 2026-06-30 08:51:19.435519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4accaa0a5434'
down_revision: Union[str, None] = '0b02a3bf0a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_document_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_client_document_types_is_active'), 'client_document_types', ['is_active'], unique=False)
    op.add_column('client_documents', sa.Column('document_type_id', sa.String(length=36), nullable=True))
    op.alter_column('client_documents', 'document_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_client_documents_document_type_id'), 'client_documents', ['document_type_id'], unique=False)
    op.create_foreign_key(None, 'client_documents', 'client_document_types', ['document_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_documents', type_='foreignkey')
    op.drop_index(op.f('ix_client_documents_document_type_id'), table_name='client_documents')
    op.alter_column('client_documents', 'document_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('client_documents', 'document_type_id')
    op.drop_index(op.f('ix_client_document_types_is_active'), table_name='client_document_types')
    op.drop_table('client_document_types')
    # ### end Alembic commands ###
