"""add district postal_code fields

Revision ID: 55d3c3163e77
Revises: 0b02a3bf0a93
Create Date: 2026-06-30 08:48:48.599187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55d3c3163e77'
down_revision: Union[str, None] = '0b02a3bf0a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Platform DB tables — managed by Alembic.
    # Per-client DB tables (org_companies.district, org_branches.district,
    # employees.current_district, employees.permanent_district) live in
    # tenant databases and are handled by _COLUMN_MIGRATIONS in client_db.py.
    op.add_column('client_billing_profiles', sa.Column('district', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('district', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('postal_code', sa.String(length=20), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'postal_code')
    op.drop_column('clients', 'district')
    op.drop_column('client_billing_profiles', 'district')
    # ### end Alembic commands ###
