"""drop_portal_tables_from_platform_db

Revision ID: a2ef1b40fab0
Revises: 1e7758f4eac0
Create Date: 2026-06-03 05:09:57.203889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a2ef1b40fab0'
down_revision: Union[str, None] = '1e7758f4eac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_user_roles')
    op.drop_index(op.f('ix_client_login_logs_client_id'), table_name='client_login_logs')
    op.drop_index(op.f('ix_client_login_logs_created_at'), table_name='client_login_logs')
    op.drop_index(op.f('ix_client_login_logs_user_id'), table_name='client_login_logs')
    op.drop_table('client_login_logs')
    op.drop_index(op.f('ix_client_user_sessions_client_id'), table_name='client_user_sessions')
    op.drop_index(op.f('ix_client_user_sessions_jti'), table_name='client_user_sessions')
    op.drop_index(op.f('ix_client_user_sessions_user_id'), table_name='client_user_sessions')
    op.drop_table('client_user_sessions')
    op.drop_index(op.f('ix_client_portal_activity_logs_actor_id'), table_name='client_portal_activity_logs')
    op.drop_index(op.f('ix_client_portal_activity_logs_client_id'), table_name='client_portal_activity_logs')
    op.drop_index(op.f('ix_client_portal_activity_logs_created_at'), table_name='client_portal_activity_logs')
    op.drop_table('client_portal_activity_logs')
    op.drop_index(op.f('ix_client_roles_client_id'), table_name='client_roles')
    op.drop_index(op.f('ix_client_roles_client_name'), table_name='client_roles')
    op.drop_table('client_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_roles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_system_role', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_roles_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_roles_pkey'))
    )
    op.create_index(op.f('ix_client_roles_client_name'), 'client_roles', ['client_id', 'name'], unique=True)
    op.create_index(op.f('ix_client_roles_client_id'), 'client_roles', ['client_id'], unique=False)
    op.create_table('client_portal_activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('target_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['client_admin_users.id'], name=op.f('client_portal_activity_logs_actor_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_portal_activity_logs_client_id_fkey')),
    sa.ForeignKeyConstraint(['target_user_id'], ['client_admin_users.id'], name=op.f('client_portal_activity_logs_target_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_portal_activity_logs_pkey'))
    )
    op.create_index(op.f('ix_client_portal_activity_logs_created_at'), 'client_portal_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_portal_activity_logs_client_id'), 'client_portal_activity_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_portal_activity_logs_actor_id'), 'client_portal_activity_logs', ['actor_id'], unique=False)
    op.create_table('client_user_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('browser_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('logged_out_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_user_sessions_client_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['client_admin_users.id'], name=op.f('client_user_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_user_sessions_pkey'))
    )
    op.create_index(op.f('ix_client_user_sessions_user_id'), 'client_user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_client_user_sessions_jti'), 'client_user_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_client_user_sessions_client_id'), 'client_user_sessions', ['client_id'], unique=False)
    op.create_table('client_login_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('browser_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_login_logs_client_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['client_admin_users.id'], name=op.f('client_login_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_login_logs_pkey'))
    )
    op.create_index(op.f('ix_client_login_logs_user_id'), 'client_login_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_client_login_logs_created_at'), 'client_login_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_login_logs_client_id'), 'client_login_logs', ['client_id'], unique=False)
    op.create_table('client_user_roles',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['client_roles.id'], name=op.f('client_user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['client_admin_users.id'], name=op.f('client_user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('client_user_roles_pkey'))
    )
    # ### end Alembic commands ###
