"""initial_schema

Revision ID: c4e495a6b65e
Revises: 
Create Date: 2026-06-01 07:25:11.434920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4e495a6b65e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiries', 'enquiry_number',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('enquiries', 'email_encrypted',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('enquiries', 'phone_encrypted',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('enquiries', 'message_encrypted',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('enquiries', 'is_spam',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'consent_given',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'deletion_requested',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_lead_conversions_client_uuid'), 'lead_conversions', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_leads_converted_client_uuid'), 'leads', ['converted_client_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_converted_client_uuid'), table_name='leads')
    op.drop_index(op.f('ix_lead_conversions_client_uuid'), table_name='lead_conversions')
    op.alter_column('enquiries', 'deletion_requested',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'consent_given',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'is_spam',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('enquiries', 'message_encrypted',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('enquiries', 'phone_encrypted',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('enquiries', 'email_encrypted',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('enquiries', 'enquiry_number',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
