"""add email_hash to client_admin_users

Revision ID: e1fb35631a4e
Revises: 5940938b0c7f
Create Date: 2026-06-29 13:37:07.935848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1fb35631a4e'
down_revision: Union[str, None] = '5940938b0c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('asset_categories_category_code_key'), 'asset_categories', type_='unique')
    op.drop_constraint(op.f('asset_categories_category_name_key'), 'asset_categories', type_='unique')
    op.drop_index(op.f('ix_asset_categories_category_code'), table_name='asset_categories')
    op.create_index(op.f('ix_asset_categories_category_code'), 'asset_categories', ['category_code'], unique=True)
    op.drop_index(op.f('ix_asset_categories_category_name'), table_name='asset_categories')
    op.create_index(op.f('ix_asset_categories_category_name'), 'asset_categories', ['category_name'], unique=True)
    op.drop_constraint(op.f('asset_masters_asset_code_key'), 'asset_masters', type_='unique')
    op.drop_index(op.f('ix_asset_masters_asset_code'), table_name='asset_masters')
    op.create_index(op.f('ix_asset_masters_asset_code'), 'asset_masters', ['asset_code'], unique=True)
    op.create_index(op.f('ix_asset_masters_sub_category_id'), 'asset_masters', ['sub_category_id'], unique=False)
    op.add_column('client_admin_users', sa.Column('email_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_client_admin_users_email_hash'), 'client_admin_users', ['email_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_admin_users_email_hash'), table_name='client_admin_users')
    op.drop_column('client_admin_users', 'email_hash')
    op.drop_index(op.f('ix_asset_masters_sub_category_id'), table_name='asset_masters')
    op.drop_index(op.f('ix_asset_masters_asset_code'), table_name='asset_masters')
    op.create_index(op.f('ix_asset_masters_asset_code'), 'asset_masters', ['asset_code'], unique=False)
    op.create_unique_constraint(op.f('asset_masters_asset_code_key'), 'asset_masters', ['asset_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_asset_categories_category_name'), table_name='asset_categories')
    op.create_index(op.f('ix_asset_categories_category_name'), 'asset_categories', ['category_name'], unique=False)
    op.drop_index(op.f('ix_asset_categories_category_code'), table_name='asset_categories')
    op.create_index(op.f('ix_asset_categories_category_code'), 'asset_categories', ['category_code'], unique=False)
    op.create_unique_constraint(op.f('asset_categories_category_name_key'), 'asset_categories', ['category_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('asset_categories_category_code_key'), 'asset_categories', ['category_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
