"""client_domain_type_and_is_active

Revision ID: e4789a0f580a
Revises: b2c3d4e5f6a7
Create Date: 2026-06-02 08:29:28.641210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e4789a0f580a'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_domains', sa.Column('domain_type', sa.String(length=30), nullable=False, server_default='custom'))
    op.add_column('client_domains', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_client_domains_is_active'), 'client_domains', ['is_active'], unique=False)
    op.execute("UPDATE client_domains SET is_active = is_primary WHERE is_active IS DISTINCT FROM is_primary")
    op.alter_column('security_2fa_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_2fa_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_login_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_login_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_notification_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_notification_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_password_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_password_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_session_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_session_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('superadmin_preferences_admin_id_key'), 'superadmin_preferences', type_='unique')
    op.drop_index(op.f('ix_superadmin_preferences_admin_id'), table_name='superadmin_preferences')
    op.create_index(op.f('ix_superadmin_preferences_admin_id'), 'superadmin_preferences', ['admin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_superadmin_preferences_admin_id'), table_name='superadmin_preferences')
    op.create_index(op.f('ix_superadmin_preferences_admin_id'), 'superadmin_preferences', ['admin_id'], unique=False)
    op.create_unique_constraint(op.f('superadmin_preferences_admin_id_key'), 'superadmin_preferences', ['admin_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('security_session_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_session_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_password_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_password_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_notification_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_notification_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_login_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_login_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_2fa_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_2fa_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_client_domains_is_active'), table_name='client_domains')
    op.drop_column('client_domains', 'is_active')
    op.drop_column('client_domains', 'domain_type')
    # ### end Alembic commands ###
