"""portal_auth_invite_columns_on_client_admin_users

Revision ID: fce44016b44d
Revises: e4789a0f580a
Create Date: 2026-06-02 09:47:52.282673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fce44016b44d'
down_revision: Union[str, None] = 'e4789a0f580a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_admin_users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('client_admin_users', sa.Column('invite_token_hash', sa.Text(), nullable=True))
    op.add_column('client_admin_users', sa.Column('invite_expires_at', sa.DateTime(), nullable=True))
    op.add_column('client_admin_users', sa.Column('invite_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_admin_users', 'invite_accepted_at')
    op.drop_column('client_admin_users', 'invite_expires_at')
    op.drop_column('client_admin_users', 'invite_token_hash')
    op.drop_column('client_admin_users', 'password_hash')
    # ### end Alembic commands ###
