"""add_module_master_table

Revision ID: ffbfbee23af8
Revises: fce44016b44d
Create Date: 2026-06-02 10:42:28.783913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ffbfbee23af8'
down_revision: Union[str, None] = 'fce44016b44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_master',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=120), nullable=True),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_module', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_master')
    # ### end Alembic commands ###
