"""Organization Management — constants."""

MODULE_NAME = "Organization Management"
MODULE_CODE = "ORGANIZATION"

STATUS_ACTIVE   = "Active"
STATUS_INACTIVE = "Inactive"
ALL_STATUSES    = [STATUS_ACTIVE, STATUS_INACTIVE]

# Activity log actions
ACTION_COMPANY_CREATED      = "COMPANY_CREATED"
ACTION_COMPANY_UPDATED      = "COMPANY_UPDATED"
ACTION_COMPANY_ACTIVATED    = "COMPANY_ACTIVATED"
ACTION_COMPANY_DEACTIVATED  = "COMPANY_DEACTIVATED"
ACTION_DEPT_CREATED         = "DEPARTMENT_CREATED"
ACTION_DEPT_UPDATED         = "DEPARTMENT_UPDATED"
ACTION_DEPT_ACTIVATED       = "DEPARTMENT_ACTIVATED"
ACTION_DEPT_DEACTIVATED     = "DEPARTMENT_DEACTIVATED"
ACTION_DESIG_CREATED        = "DESIGNATION_CREATED"
ACTION_DESIG_UPDATED        = "DESIGNATION_UPDATED"
ACTION_DESIG_ACTIVATED      = "DESIGNATION_ACTIVATED"
ACTION_DESIG_DEACTIVATED    = "DESIGNATION_DEACTIVATED"
