"""Organization Management — constants."""

MODULE_NAME = "Organization Management"
MODULE_CODE = "ORGANIZATION"

STATUS_ACTIVE   = "Active"
STATUS_INACTIVE = "Inactive"
ALL_STATUSES    = [STATUS_ACTIVE, STATUS_INACTIVE]

# Branch types
BRANCH_TYPES = [
    "Head Office",
    "Corporate Office",
    "Regional Office",
    "Branch Office",
    "Warehouse",
    "Project Site",
]

# Employee work modes
WORK_MODES = ["Onsite", "Work From Home", "Hybrid", "Remote"]

# Activity log actions — companies
ACTION_COMPANY_CREATED      = "COMPANY_CREATED"
ACTION_COMPANY_UPDATED      = "COMPANY_UPDATED"
ACTION_COMPANY_ACTIVATED    = "COMPANY_ACTIVATED"
ACTION_COMPANY_DEACTIVATED  = "COMPANY_DEACTIVATED"

# Activity log actions — branches
ACTION_BRANCH_CREATED       = "BRANCH_CREATED"
ACTION_BRANCH_UPDATED       = "BRANCH_UPDATED"
ACTION_BRANCH_ACTIVATED     = "BRANCH_ACTIVATED"
ACTION_BRANCH_DEACTIVATED   = "BRANCH_DEACTIVATED"

# Activity log actions — departments
ACTION_DEPT_CREATED         = "DEPARTMENT_CREATED"
ACTION_DEPT_UPDATED         = "DEPARTMENT_UPDATED"
ACTION_DEPT_HEAD_CHANGED    = "DEPARTMENT_HEAD_CHANGED"
ACTION_DEPT_ACTIVATED       = "DEPARTMENT_ACTIVATED"
ACTION_DEPT_DEACTIVATED     = "DEPARTMENT_DEACTIVATED"

# Activity log actions — designations
ACTION_DESIG_CREATED        = "DESIGNATION_CREATED"
ACTION_DESIG_UPDATED        = "DESIGNATION_UPDATED"
ACTION_DESIG_ACTIVATED      = "DESIGNATION_ACTIVATED"
ACTION_DESIG_DEACTIVATED    = "DESIGNATION_DEACTIVATED"
