"""
Module Registry — central catalog of all platform modules.

module_master.name MUST match the string used in client_modules.module_name
so the two tables join cleanly without a foreign-key migration.

parent_module_code = None  → top-level module (shown as a card)
parent_module_code = <code> → child module (shown inside parent modal only)
"""

MODULE_CATALOG = [
    # ── System (always present, not toggleable by admin) ─────────────────────
    {
        "code": "USER_MANAGEMENT",
        "name": "User Management",
        "description": "Workspace users, roles, login logs, and session management",
        "route": "user-management",
        "icon": "user-plus",
        "display_order": 1,
        "is_system_module": True,
        "parent_module_code": None,
    },

    # ── Top-level business modules ────────────────────────────────────────────
    {
        "code": "ORGANIZATION",
        "name": "Organization Management",
        "description": "Manage companies, organization structure and employees",
        "route": "org",
        "icon": "building",
        "display_order": 5,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "hrms",
        "name": "HRMS",
        "description": "Manage the complete employee lifecycle — recruitment, attendance, leave, and payroll",
        "route": "hrms",
        "icon": "briefcase",
        "display_order": 20,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "assets",
        "name": "Asset Management",
        "description": "Manage company assets and assignments across locations and teams",
        "route": "assets",
        "icon": "package",
        "display_order": 30,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "helpdesk",
        "name": "Helpdesk",
        "description": "Support ticket and service-request management with SLA tracking",
        "route": "helpdesk",
        "icon": "headphones",
        "display_order": 40,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "billing",
        "name": "Billing Management",
        "description": "Invoices, payments, and financial records for the workspace",
        "route": "billing",
        "icon": "credit-card",
        "display_order": 50,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "reports",
        "name": "Reports",
        "description": "Analytics dashboards and exportable reports across all modules",
        "route": "reports",
        "icon": "bar-chart",
        "display_order": 60,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "knowledge",
        "name": "Knowledge Base",
        "description": "Internal wiki, SOPs, and documentation with version control",
        "route": "knowledge",
        "icon": "book",
        "display_order": 70,
        "is_system_module": False,
        "parent_module_code": None,
    },
    {
        "code": "workflow",
        "name": "Workflow Engine",
        "description": "Process automation and multi-step approval workflows",
        "route": "workflow",
        "icon": "git-branch",
        "display_order": 80,
        "is_system_module": False,
        "parent_module_code": None,
    },

    # ── Children of Organization Management ──────────────────────────────────
    {
        "code": "org_companies",
        "name": "Companies",
        "description": "Manage company entities and corporate profiles",
        "route": "org/companies",
        "icon": "building",
        "display_order": 501,
        "is_system_module": False,
        "parent_module_code": "ORGANIZATION",
    },
    {
        "code": "org_branches",
        "name": "Branches",
        "description": "Office branches and geographic locations",
        "route": "org/branches",
        "icon": "building",
        "display_order": 502,
        "is_system_module": False,
        "parent_module_code": "ORGANIZATION",
    },
    {
        "code": "org_departments",
        "name": "Departments",
        "description": "Departments and organisational units",
        "route": "org/departments",
        "icon": "building",
        "display_order": 503,
        "is_system_module": False,
        "parent_module_code": "ORGANIZATION",
    },
    {
        "code": "org_designations",
        "name": "Designations",
        "description": "Job titles and designations catalog",
        "route": "org/designations",
        "icon": "building",
        "display_order": 504,
        "is_system_module": False,
        "parent_module_code": "ORGANIZATION",
    },
    {
        "code": "org_employees",
        "name": "Employees",
        "description": "Employee profiles, records and lifecycle management",
        "route": "employees",
        "icon": "user-plus",
        "display_order": 505,
        "is_system_module": False,
        "parent_module_code": "ORGANIZATION",
    },
    {
        "code": "org_emp_docs",
        "name": "Employee Documents",
        "description": "Employee document management and storage",
        "route": "employee-documents",
        "icon": "book",
        "display_order": 506,
        "is_system_module": False,
        "parent_module_code": "ORGANIZATION",
    },

    # ── Children of HRMS ─────────────────────────────────────────────────────
    {
        "code": "recruitment",
        "name": "Recruitment",
        "description": "Job postings, applicant tracking, and hiring pipelines",
        "route": "recruitment",
        "icon": "user-plus",
        "display_order": 2001,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_interview",
        "name": "Interview Management",
        "description": "Schedule and track interview rounds for candidates",
        "route": "hrms/interviews",
        "icon": "briefcase",
        "display_order": 2002,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_onboarding",
        "name": "Employee Onboarding",
        "description": "Structured onboarding workflows for new hires",
        "route": "hrms/onboarding",
        "icon": "briefcase",
        "display_order": 2003,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_attendance",
        "name": "Attendance Management",
        "description": "Track daily attendance, shifts, and working hours",
        "route": "hrms/attendance",
        "icon": "briefcase",
        "display_order": 2004,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_leave",
        "name": "Leave Management",
        "description": "Leave policies, requests, approvals, and holiday calendar",
        "route": "hrms/leave",
        "icon": "briefcase",
        "display_order": 2005,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_payroll",
        "name": "Payroll Management",
        "description": "Payroll processing, salary components, and disbursement",
        "route": "hrms/payroll",
        "icon": "briefcase",
        "display_order": 2006,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_loans",
        "name": "Employee Loan Management",
        "description": "Employee loan requests, approvals, and repayment tracking",
        "route": "hrms/loans",
        "icon": "briefcase",
        "display_order": 2007,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },
    {
        "code": "hrms_expenses",
        "name": "Expense & Reimbursements",
        "description": "Employee expense claims and reimbursement workflows",
        "route": "hrms/expenses",
        "icon": "briefcase",
        "display_order": 2008,
        "is_system_module": False,
        "parent_module_code": "hrms",
    },

    # ── Children of Asset Management ─────────────────────────────────────────
    {
        "code": "assets_inventory",
        "name": "Asset Inventory",
        "description": "Catalog and track all company assets",
        "route": "assets/inventory",
        "icon": "package",
        "display_order": 3001,
        "is_system_module": False,
        "parent_module_code": "assets",
    },
    {
        "code": "assets_maintenance",
        "name": "Asset Maintenance",
        "description": "Maintenance schedules and service logs for assets",
        "route": "assets/maintenance",
        "icon": "package",
        "display_order": 3002,
        "is_system_module": False,
        "parent_module_code": "assets",
    },
    {
        "code": "assets_audits",
        "name": "Asset Audits",
        "description": "Periodic asset audits and verification workflows",
        "route": "assets/audits",
        "icon": "package",
        "display_order": 3003,
        "is_system_module": False,
        "parent_module_code": "assets",
    },
    {
        "code": "assets_requests",
        "name": "Asset Requests",
        "description": "Employee asset request and assignment management",
        "route": "assets/requests",
        "icon": "package",
        "display_order": 3004,
        "is_system_module": False,
        "parent_module_code": "assets",
    },
]

MODULE_CODES = [m["code"] for m in MODULE_CATALOG]
MODULE_NAMES = [m["name"] for m in MODULE_CATALOG]
