export const COUNTRY_CODES = [
  { iso2: "us", name: "United States / Canada", dial: "+1" },
  { iso2: "gb", name: "United Kingdom", dial: "+44" },
  { iso2: "in", name: "India", dial: "+91" },
  { iso2: "au", name: "Australia", dial: "+61" },
  { iso2: "ae", name: "United Arab Emirates", dial: "+971" },
  { iso2: "sg", name: "Singapore", dial: "+65" },
  { iso2: "de", name: "Germany", dial: "+49" },
  { iso2: "fr", name: "France", dial: "+33" },
  { iso2: "es", name: "Spain", dial: "+34" },
  { iso2: "it", name: "Italy", dial: "+39" },
  { iso2: "nl", name: "Netherlands", dial: "+31" },
  { iso2: "be", name: "Belgium", dial: "+32" },
  { iso2: "ch", name: "Switzerland", dial: "+41" },
  { iso2: "se", name: "Sweden", dial: "+46" },
  { iso2: "no", name: "Norway", dial: "+47" },
  { iso2: "dk", name: "Denmark", dial: "+45" },
  { iso2: "fi", name: "Finland", dial: "+358" },
  { iso2: "ie", name: "Ireland", dial: "+353" },
  { iso2: "pt", name: "Portugal", dial: "+351" },
  { iso2: "at", name: "Austria", dial: "+43" },
  { iso2: "pl", name: "Poland", dial: "+48" },
  { iso2: "cz", name: "Czechia", dial: "+420" },
  { iso2: "gr", name: "Greece", dial: "+30" },
  { iso2: "ro", name: "Romania", dial: "+40" },
  { iso2: "hu", name: "Hungary", dial: "+36" },
  { iso2: "ru", name: "Russia", dial: "+7" },
  { iso2: "ua", name: "Ukraine", dial: "+380" },
  { iso2: "tr", name: "Türkiye", dial: "+90" },
  { iso2: "il", name: "Israel", dial: "+972" },
  { iso2: "sa", name: "Saudi Arabia", dial: "+966" },
  { iso2: "qa", name: "Qatar", dial: "+974" },
  { iso2: "kw", name: "Kuwait", dial: "+965" },
  { iso2: "bh", name: "Bahrain", dial: "+973" },
  { iso2: "om", name: "Oman", dial: "+968" },
  { iso2: "eg", name: "Egypt", dial: "+20" },
  { iso2: "za", name: "South Africa", dial: "+27" },
  { iso2: "ng", name: "Nigeria", dial: "+234" },
  { iso2: "ke", name: "Kenya", dial: "+254" },
  { iso2: "gh", name: "Ghana", dial: "+233" },
  { iso2: "ma", name: "Morocco", dial: "+212" },
  { iso2: "cn", name: "China", dial: "+86" },
  { iso2: "hk", name: "Hong Kong", dial: "+852" },
  { iso2: "tw", name: "Taiwan", dial: "+886" },
  { iso2: "jp", name: "Japan", dial: "+81" },
  { iso2: "kr", name: "South Korea", dial: "+82" },
  { iso2: "my", name: "Malaysia", dial: "+60" },
  { iso2: "id", name: "Indonesia", dial: "+62" },
  { iso2: "th", name: "Thailand", dial: "+66" },
  { iso2: "ph", name: "Philippines", dial: "+63" },
  { iso2: "vn", name: "Vietnam", dial: "+84" },
  { iso2: "pk", name: "Pakistan", dial: "+92" },
  { iso2: "bd", name: "Bangladesh", dial: "+880" },
  { iso2: "lk", name: "Sri Lanka", dial: "+94" },
  { iso2: "np", name: "Nepal", dial: "+977" },
  { iso2: "nz", name: "New Zealand", dial: "+64" },
  { iso2: "br", name: "Brazil", dial: "+55" },
  { iso2: "mx", name: "Mexico", dial: "+52" },
  { iso2: "ar", name: "Argentina", dial: "+54" },
  { iso2: "cl", name: "Chile", dial: "+56" },
  { iso2: "co", name: "Colombia", dial: "+57" },
  { iso2: "pe", name: "Peru", dial: "+51" },
];

export const flagUrl = (iso2) => `https://flagcdn.com/24x18/${iso2}.png`;
export const flagUrl2x = (iso2) => `https://flagcdn.com/48x36/${iso2}.png`;
